name: Game Day Notifications

on:
   schedule:
      - cron: '30 18 * * *'

jobs:
   game-day-notification-check:
      runs-on: ubuntu-latest

      steps:
         - name: Check for game day status
           run: curl -XPOST 'https://www.icepakhockey.com/api/notifications/game-day'
